using System;
using System.IO;
using System.Collections.Generic;

namespace lesson2
{
    class MainClass
    {
        public static void Main(string[] args)
        {

            //read csv file
            //user picks option to either create new or list current
            //create array for ticket objects
            //ticket


            string file = "tickets.csv";
            StreamReader ticketFile = new StreamReader(file);
            int ticketNumber = 0;
            List<Tickets> Ticket = new List<Tickets>();
            while (!ticketFile.EndOfStream)
            {
                string line = ticketFile.ReadLine();
                string[] arg = line.Split('|');
                ticketNumber = Int32.Parse(arg[0]);
                Ticket.Add(new Tickets(Int32.Parse(arg[0]),arg[1],arg[2],arg[3],arg[4],arg[5],arg[6]));

            }
          
            ticketFile.Close();

            Console.WriteLine("Welcome to our Ticket system");
            
            MenuOptions(ticketNumber, Ticket);
        }
        public static void MenuOptions(int ticketNumber, List<Tickets> Ticket)
        {
            string choice;
            do
            {
                Console.WriteLine("Menu:");
                Console.WriteLine("(1) Create a New Ticket");
                Console.WriteLine("(2) List Current Tickets");
                choice = Console.ReadLine();
            } while (choice != "1" && choice != "2" && choice !="3");

            if (choice == "1")
            {
                ticketNumber++;
                CreateTicket(ticketNumber, Ticket);
            }
            if (choice == "2")
            {
                ListTickets(ticketNumber, Ticket);
            }
            if (choice == "3")
            {
                eraseAll();
            }
        }

        private static void eraseAll()
        {
            
        }

        public static void CreateTicket(int ticketNumber, List<Tickets> Ticket)
        {
            string file = "tickets.csv";
            string summary, status = "Open", priority, submitter, assignedTo, watching = ""; //assigned to can be generated by number of tickets held;
            //StreamWriter ticketFile = new StreamWriter(file);

            Console.WriteLine("Please enter a brief summary of the issue");
            summary = Console.ReadLine();
            Console.WriteLine("What is the priority of this issue (High, Normal, Low");
            priority = Console.ReadLine();
            Console.WriteLine("What is your Name?");
            submitter = Console.ReadLine();
            Console.WriteLine("Who should this ticket be assigned to?");
            assignedTo = Console.ReadLine();
            Console.WriteLine("this code should write");
            Console.WriteLine("Who will be watching this ticket?(type 'none' when done)");
            Console.WriteLine("so should this");
            while(watching != "none"){
            watching = Console.ReadLine();
            }



            if (!File.Exists(file))
            {
                using (StreamWriter ticketFile = File.CreateText(file)) { 
                    
                    //Tickets.Add(ticketNumber);
                    ticketFile.WriteLine("{0}|{1}|{2}|{3}|{4}|{5}|{6}", ticketNumber, summary, status, priority, submitter, assignedTo, watching);
                    Console.WriteLine("A Ticket has been created for you.");
                    ticketFile.Close();
                }
            }
            else
            {

                StreamWriter ticketFile = new StreamWriter(file);
                {
                    ticketFile.WriteLine("{0}|{1}|{2}|{3}|{4}|{5}|{6}", ticketNumber, summary, status, priority, submitter, assignedTo, watching);
                    Console.WriteLine("A Ticket has been created for you.");
                    ticketFile.Close();

                }
            }
            Ticket.Add(new Tickets(ticketNumber,summary, status, priority, submitter, assignedTo, watching));

            MenuOptions(ticketNumber, Ticket);

        }
        public static void ListTickets(int ticketNumber,List<Tickets> Ticket)
        {
            string file = "tickets.csv";

            if (File.Exists(file))
            {
                StreamReader ticketFile = new StreamReader(file);
                while (!ticketFile.EndOfStream)
                {
                    string line = ticketFile.ReadLine();
                    string[] arg = line.Split('|');
                    //Console.WriteLine("Ticket #: {0}\nStatus: {1}\nPriority: {2}\nSubmitted by: {3}\n",arg[0],arg[1],arg[2],arg[3]);

                }
                ticketFile.Close();

            }
            else
            {
                Console.WriteLine("Error: File does not exist");
            }
        
            for (int i = 0; i < Ticket.Count;i++){
                Console.WriteLine(Ticket[i].ticketNumber);
            }
        MenuOptions(ticketNumber, Ticket);
        }
    }
}
