using System;
using System.IO;

namespace lesson2
{
    class MainClass
    {
        public static void Main(string[] args)
        {

            //read csv file
            //user picks option to either create new or list current
            //create array for ticket objects
            //ticket


            string file = "tickets.csv";
            StreamReader ticketFile = new StreamReader(file);
            int ticket = 0;
            while (!ticketFile.EndOfStream)
            {
                string line = ticketFile.ReadLine();
                string[] arg = line.Split('|');
                ticket = Int32.Parse(arg[0]);
            }
            ticketFile.Close();

            Console.WriteLine("Welcome to our Ticket system");
            MenuOptions(ticket);
        }
        public static void MenuOptions(int ticket)
        {
            string choice;
            do
            {
                Console.WriteLine("Menu:");
                Console.WriteLine("(1) Create a New Ticket");
                Console.WriteLine("(2) List Current Tickets");
                choice = Console.ReadLine();
            } while (choice != "1" && choice != "2" && choice !="3");

            if (choice == "1")
            {
                ticket++;
                CreateTicket(ticket);
            }
            if (choice == "2")
            {
                ListTickets(ticket);
            }
            if (choice == "3")
            {
                eraseAll();
            }
        }

        private static void eraseAll()
        {
            
        }

        public static void CreateTicket(int ticket)
        {
            string file = "tickets.csv";
            //int ticket = 0;
            string summary, status = "Open", priority, submitter, assignedTo, watching = ""; //assigned to can be generated by number of tickets held;
            //StreamWriter ticketFile = new StreamWriter(file);

            Console.WriteLine("Please enter a brief summary of the issue");
            summary = Console.ReadLine();
            Console.WriteLine("What is the priority of this issue (High, Normal, Low");
            priority = Console.ReadLine();
            Console.WriteLine("What is your Name?");
            submitter = Console.ReadLine();
            Console.WriteLine("Who should this ticket be assigned to?");
            assignedTo = Console.ReadLine();

            if (!File.Exists(file))
            {
                using (StreamWriter ticketFile = File.CreateText(file)) { 
                    ticketFile.WriteLine("{0}|{1}|{2}|{3}|{4}|{5}|{6}", ticket, summary, status, priority, submitter, assignedTo, watching);
                    Console.WriteLine("A Ticket has been created for you.");
                    ticketFile.Close();
                }
            }
            else
            {

                StreamWriter ticketFile = new StreamWriter(file);
                {
                    ticketFile.WriteLine("{0}|{1}|{2}|{3}|{4}|{5}|{6}", ticket, summary, status, priority, submitter, assignedTo, watching);
                    Console.WriteLine("A Ticket has been created for you.");
                    ticketFile.Close();

                }
            }
            MenuOptions(ticket);

        }
        public static void ListTickets(int ticket)
        {
            string file = "tickets.csv";

            if (File.Exists(file))
            {
                StreamReader ticketFile = new StreamReader(file);
                while (!ticketFile.EndOfStream)
                {
                    string line = ticketFile.ReadLine();
                    string[] arg = line.Split('|');
                    Console.WriteLine("Ticket #: {0}\nStatus: {1}\nPriority: {2}\nSubmitted by: {3}\n",arg[0],arg[1],arg[2],arg[3]);

                }
            }
            else
            {
                Console.WriteLine("Error: File does not exist");
            }
            MenuOptions(ticket);
        }
    }
}
